version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - 8080:8080
  frontend:
    depends_on:
      - backend
    build: ./frontend
    ports:
      - 80:80
    environment:
      - API_URL=http://backend:8080
